#!/bin/bash

# List sessions with tmuxp
sessions=($(tmuxp ls))
sessions+=("<new>")

# Fuzzy find to select a session
title="Select Tmux session to load, or start a <new> one"
ptitle="Workspace YAML file"
preview="if [ -e $TMUXP_CONFIGDIR/{}.* ]; then cat $TMUXP_CONFIGDIR/{}.yml; else echo 'New session...'; fi | sed -E 's/([a-zA-Z2-9_-]+:)/\x1b[31m\1\x1b[0m/g'"
# TODO: improve vi-style key bindings
selected=$(printf "%s\n" "${sessions[@]}" | fzf -i +s --tac \
    --border=rounded --border-label="╢ $title ╟" --border-label-pos=0:bottom \
    --margin=5 --padding=0 \
    --preview="bash -c \"$preview\"" --preview-label="╢ $ptitle ╟" --preview-label-pos=0:top \
    --bind="j:down,k:up,s:jump,p:toggle-preview" \
    --bind="h:backward-char,l:forward-char,e:forward-word,b:backward-word" \
    --bind="d:clear-query" \
    --bind="D:preview-half-page-down,U:preview-half-page-up" \
    --bind="start:enable-search+unbind(e,s,p,h,l,é,b,d,y,E,U,c,x,X,i,a,A,I)" \
    --bind="i:enable-search+unbind(j,k,s,p,h,l,e,b,d,y,E,U,c,x,X,i,a,A,I)" \
    --bind="a:enable-search+unbind(j,k,s,p,h,l,e,b,d,y,E,U,c,x,X,i,a,A,I)+forward-char" \
    --bind="A:enable-search+unbind(j,k,s,p,h,l,e,b,d,y,E,U,c,x,X,i,a,A,I)+end-of-line" \
    --bind="I:enable-search+unbind(j,k,s,p,h,l,e,b,d,y,E,U,c,x,X,i,a,A,I)+beginning-of-line" \
    --bind="esc:disable-search+rebind(j,k,s,p,h,l,e,b,d,y,E,U,c,x,X,i,a,A,I)" )

if [[ -z $selected ]]; then
    exit 0
fi

# Handle the user's choice
if [ "$selected" == "<new>" ]; then
    # Use the current directory name as the session name
    session_name=$(basename "$PWD")

    tmux new-session -A -s i"$session_name" -t "Main"
else
    # Load session with tmuxp
    tmuxp load "$selected"
fi
